# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sample-swiftui' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample-swiftui
pod 'PayTabsSDK', '~> 6.6.19'

end
