workflows:
  publish_podspec:
    name: Publish Podspec (Version Increment & CocoaPods)
    max_build_duration: 30
    environment:
      xcode: latest
      cocoapods: default
      groups:
        - environment variables
      # Environment variables are set in the group above:
      # - COCOAPODS_USERNAME: Your CocoaPods username
      # - COCOAPODS_PASSWORD: Your CocoaPods password/token
      # - GITHUB_TOKEN: GitHub token for creating tags (optional if using git)
    cache:
      cache_paths:
        - ~/.cocoapods
    scripts:
      - name: Extract current version from podspec
        script: bash ci-scripts/extract_version.sh
      - name: Update podspec version
        script: bash ci-scripts/update_podspec.sh
      - name: Create and push git tag
        script: bash ci-scripts/create_and_push_tag.sh
      - name: Validate podspec
        script: bash ci-scripts/validate_podspec.sh
      - name: Setup CocoaPods trunk authentication
        script: bash ci-scripts/setup_trunk_auth.sh
      - name: Push podspec to CocoaPods trunk
        script: bash ci-scripts/push_podspec_trunk.sh

  ios_swiftui_firebase:
    name: iOS SwiftUI - Firebase Distribution
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      groups:
        - environment variables
      vars:
        XCODE_WORKSPACE: sample-swiftui/sample-swiftui.xcworkspace
        XCODE_SCHEME: sample-swiftui
        EXPORT_METHOD: ad-hoc
        FIREBASE_APP_ID: $FIREBASE_APP_ID    # Firebase iOS App ID for paytabs.sdk.ios.native.simple
        FIREBASE_GROUPS: "Testers"           # Default distribution group
        RELEASE_NOTES: "Automated build from Codemagic"
    cache:
      cache_paths:
        - ~/.cocoapods
        - sample-swiftui/Pods
    scripts:
      - name: Place GoogleService-Info.plist (optional)
        script: bash ci-scripts/place_google_service.sh
      - name: Install pods
        script: bash ci-scripts/install_pods_swiftui.sh
      - name: Clean and archive
        script: bash ci-scripts/archive_swiftui.sh
      - name: Export .ipa
        script: bash ci-scripts/export_ipa.sh
      - name: Install Firebase CLI
        script: bash ci-scripts/install_firebase_cli.sh
      - name: Distribute to Firebase App Distribution
        script: bash ci-scripts/distribute_firebase.sh
    artifacts:
      - build/export/*.ipa
      - build/App.xcarchive
      - $CM_BUILD_DIR/ExportOptions.plist

  ios_testflight:
    name: iOS TestFlight
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: $APP_STORE_CONNECT_KEY_NAME
    environment:
      groups:
        - environment variables
      ios_signing:
        provisioning_profiles:
          - $PROFILE
        certificates:
          - $CERTIFICATE
      xcode: latest
      cocoapods: default

      vars:
        XCODE_WORKSPACE: sample-swiftui/sample-swiftui.xcworkspace
        XCODE_SCHEME: sample-swiftui
        EXPORT_METHOD: app-store
        RELEASE_NOTES: "Automated build from Codemagic"
        APP_STORE_APPLE_ID: 6754967249
    cache:
      cache_paths:
        - ~/.cocoapods
        - sample-swiftui/Pods
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Place GoogleService-Info.plist (optional)
        script: bash ci-scripts/place_google_service.sh
      - name: Install pods
        script: bash ci-scripts/install_pods_swiftui.sh
      - name: Build IPA for App Store distribution
        script: |
          xcode-project build-ipa \
          --workspace "$XCODE_WORKSPACE" \
          --scheme "$XCODE_SCHEME" \
          --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/archive/*.xcarchive
      - $CM_BUILD_DIR/ExportOptions.plist
    publishing:
      email:
        recipients:
          - mobile.devop@paytabs.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false