# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sample-run' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample-run
  pod 'BIObjCHelpers'
  pod 'AFNetworking'
  pod 'Mantle'
  pod 'Reachability'
  pod 'SDWebImage'
  pod 'DGActivityIndicatorView'
  pod 'Lockbox'
  pod 'YLGIFImage'
  pod 'SBJson'
  pod 'PINCache'
  pod 'IQKeyboardManager'
  
  target 'sample-runTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sample-runUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

