
target 'PayTabs Sample' do
 pod 'PayTabs', '~> 4.3.0'
end

#To enable bitcode flag
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
            config.build_settings['ENABLE_BITCODE'] = 'YES'
        end
    end
end
