# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sample-run
  pod 'BIObjCHelpers'
  pod 'IQKeyboardManager', '~> 4.0.2'
  pod 'AFNetworking'
  pod 'Mantle'
  pod 'Reachability'
  pod 'Lockbox'
  pod 'SBJson'
  pod 'PINCache'
  pod 'MBProgressHUD', '~> 1.1.0'
  
end
